# unittests

name: dtable-events test

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: apt install
      run: |
        sudo apt-get update --fix-missing || true
        sudo apt-get install -y libevent-dev libcurl4-openssl-dev libglib2.0-dev
        sudo apt-get install -y uuid-dev intltool libsqlite3-dev build-essential
        sudo apt-get install -y libarchive-dev libtool libjansson-dev valac
        sudo apt-get install -y libfuse-dev cmake re2c flex sqlite3
        sudo apt-get install -y libssl-dev libldap2-dev libonig-dev
        sudo apt-get install -y libxml2 libxml2-dev
        sudo apt-get install -y python-dev libsasl2-dev gcc libjwt-dev

    - name: clone and build
      run: |
        git clone --depth=1 --branch=master https://github.com/haiwen/seafile-test-deploy /tmp/seafile-test-deploy
        git clone https://github.com/haiwen/seafobj /tmp/seafobj
        cd /tmp/seafile-test-deploy && git fetch origin master:master && git checkout master
        ./bootstrap.sh

    - name: pip install
      run: |
        cd /tmp/seafobj && pip install -r requirements.txt  && pip install pylibmc
        cd $GITHUB_WORKSPACE && pip install -r test-requirements.txt

    - name: test sql
      run: |
        cd $GITHUB_WORKSPACE
        export CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data IS_PRO_VERSION=True
        ./dtable_events/tests/test.sh init && ./dtable_events/tests/test.sh test
